<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ankit_lappy" failures="1" tests="2" name="Default test" time="2.161" errors="0" timestamp="2025-06-01T13:26:37 CDT">
  <testcase classname="testNGPractice.testng_Practice5" name="Scenario14" time="2.036">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNGPractice.testng_Practice5.Scenario14() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNGPractice.testng_Practice5.Scenario14() didn't finish within the time-out 2000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at testNGPractice.testng_Practice5.Scenario14(testng_Practice5.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- Scenario14 -->
  <testcase classname="testNGPractice.testng_Practice5" name="Scenario13" time="0.0">
    <skipped/>
  </testcase> <!-- Scenario13 -->
</testsuite> <!-- Default test -->
